<?php
$license_data = Mage::getSingleton('core/session')->getLicensefileValues();
$license_file_mapdata = Mage::getSingleton('core/session')->getLicensefileMappingdata();
$license_file_createdby = Mage::getSingleton('core/session')->getLicensefileCreatedBy();
$maintenanceProducts = Mage::getSingleton('core/session')->getMaintenanceProductsCollection();
$notificationAboutExpiry = Mage::getSingleton('core/session')->getNotificationAboutExpiry();
$finalized=$discontinued_prod=$product_with_issues=array();
$softwareProd=0;

foreach ($license_data as $key =>$value){
    if(isset($license_file_mapdata[$key]) && $license_file_mapdata[$key]!=''){
        $finalized[$key]=$value;
    } else if(preg_match('/^payment-gateways-/', $key)&& !isset($license_file_mapdata[$key])){
        $finalized['payment-gateways-????']=$value;
    }
}

foreach ($finalized as $key =>$value){
    if(isset($license_file_mapdata[$key]) && $license_file_mapdata[$key]!=''){
        $sku=$license_file_mapdata[$key];
        $_product = Mage::getModel('catalog/product')->loadByAttribute('sku',$sku);
        if(is_object($_product))
            $final_mapped_data[$sku] = $value;
        else
            $discontinued_prod[]=$key;
    }else{
        $product_with_issues[]=$key;
        $discontinued_prod[]=$key;
    }
}



if(!empty($finalized)){
//    echo '<pre>';
//    print_r($final_mapped_data);
    foreach ($final_mapped_data as $sku => $qty){
        $qty =1;
        $_product = Mage::getModel('catalog/product')->loadByAttribute('sku',$sku);
        $attribTxt = $_product->getAttributeText('product_type');
        $item_price=$this->helper('tax')->getPrice($_product, $_product->getFinalPrice($qty));
        $item_price=$item_price*$qty;
        if(strtolower($attribTxt)=='software product')
            $softwareProd=$softwareProd+$item_price;
        echo $softwareProd;
            Mage::getSingleton('core/session')->setsoftwareProdPrice($softwareProd);

                //echo $item_price;
            }

}
/**
 * From the finalized list check for existence of the product in online Database.
 *
 **/


?>
<?php
if(!$notificationAboutExpiry){?>
    <ul class="messages" xmlns="http://www.w3.org/1999/html">
        <li class="error-msg">
            <ul>
                <li>
                   <span>
                       <?php

                       echo $this->__('Your support is expired, please renew it.');

                       ?>
					</span>
                </li>
            </ul>
        </li>
    </ul>
<?php } ?>
<form name="maintenanceUpgrade" action="<?php echo Mage::getUrl('paytech/index/uploadLicense/'); ?>" method="post">
<table class="data-table" id="maintenace-products-table">
    <col />
    <col />
    <col />
    <col />
    <col />
    <col />
    <thead>
    <tr>
        <th><?php echo $this->__('Item') ?></th>
        <th><?php echo $this->__('Item Name') ?></th>
        <th><?php echo $this->__('Subtotal') ?></th>
    </tr>
    </thead>
    <tbody>
<?php
$_odd = '';
$current_currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
$maintenanceProducts = Mage::getSingleton('core/session')->getMaintenanceProductsCollection();
if(isset($maintenanceProducts)){
    foreach($maintenanceProducts as $maintenanceProduct){
        $_product = Mage::getModel('catalog/product')->loadByAttribute('sku', $maintenanceProduct);
    ?>

<tr>

    <td>

    <input type="radio" name="maintenanceProduct" id="maintenanceProduct" value="<?php echo $maintenanceProduct;?>"
           style="width:25px; height: 45px">
        <img src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(75,75); ?>" />
    </td>
    <td>
        <span class="nobr"><?php echo $_product->getName();?></span>
    </td>
    <td>
        <?php
        $support=true;
        $percent=$_product->getData('tot_software_perc');
        //print_r($softwareProd);
        //echo $percent;

        $calculatedPrice=$softwareProd/100*$percent;
        $item_price=$_product->getFinalPrice();
        //echo $item_price;
        if($item_price>$calculatedPrice)
            $item_price=$calculatedPrice;
//                $item_price = $_product->getFinalPrice();

        //echo $item_price;

        if($current_currency_code == 'NZD'){
            $price=Mage::helper('directory')->currencyConvert((float)$item_price, 'AUD', 'NZD');
            echo "NZ$ ".number_format($price, '2', '.', ',');
        }else{
            echo "AU$ ".number_format($item_price, '2', '.', ',');
        }
        ?>

    </td>

</tr>

    <?php }} ?>
</tbody>
</table>
    <input type="hidden" id="maintenanceProductPrice" name="maintenanceProductPrice" value="">


<div class="quote" style="float:right;margin:10px 0px">
    <input type="submit" style="display: block;background: #b21116;-moz-border-radius: 5px;-webkit-border-radius: 5px;padding: 3px 6px;text-align: center;
    white-space: nowrap;color: #fff;text-decoration: none;font-family: 'Istok Web',Arial,Helvetica,sans-serif;width: inherit;text-transform: uppercase;" value="Proceed">
</div>
</form>
<script>
    jQuery('document').ready(function(){
        /*jQuery("input[type='radio']").click(function(){
            alert(jQuery(this).html());
            jQuery(this).closest('tr').css('bakground','red');
         //   var radioValue = jQuery("input[name='maintenanceProduct']:checked").val();

        });*/
        jQuery( "#maintenace-products-table tbody tr" ).on( "click", function() {

            var itemclick=jQuery(this).find("td:last").html();

            var itemprice=itemclick.trim().split(' ');
            jQuery('#maintenanceProductPrice').val(itemprice[1]);

        });
    })
</script>