<div class="page-title">
    <h1><?php echo $this->__('Quote for the license file') ?></h1>    	
</div>
<?php

$license_data = Mage::getSingleton('core/session')->getLicensefileValues();
$license_file_mapdata = Mage::getSingleton('core/session')->getLicensefileMappingdata();
$license_file_createdby = Mage::getSingleton('core/session')->getLicensefileCreatedBy();
$maintenanceProducts = Mage::getSingleton('core/session')->getMaintenanceProductsCollection();
$notificationAboutExpiry = Mage::getSingleton('core/session')->getNotificationAboutExpiry();
$finalized=$discontinued_prod=$product_with_issues=array();

/**Loop to get the finalized list of products. For this we have to check for product sku in
*license mapping file. if key exists in mapping file then it will be added to the finalized
*list.
**/
foreach ($license_data as $key =>$value){
   if(isset($license_file_mapdata[$key]) && $license_file_mapdata[$key]!=''){
		$finalized[$key]=$value;
   } else if(preg_match('/^payment-gateways-/', $key)&& !isset($license_file_mapdata[$key])){
		$finalized['payment-gateways-????']=$value;
   }
}

/**
* From the finalized list check for existence of the product in online Database. 
*
**/


foreach ($finalized as $key =>$value){

	if(isset($license_file_mapdata[$key]) && $license_file_mapdata[$key]!=''){
		$sku=$license_file_mapdata[$key];
		$_product = Mage::getModel('catalog/product')->loadByAttribute('sku',$sku);
		if(is_object($_product))
			$final_mapped_data[$sku] = $value;
		else
			$discontinued_prod[]=$key;
	}else{
		$product_with_issues[]=$key;
		$discontinued_prod[]=$key;
	}
}
if(isset($_POST['maintenanceProduct'])){
    $selectedMaintenanceProduct = $_POST['maintenanceProduct'];
    $selectedMaintenanceProductPrice = $_POST['maintenanceProductPrice'];
    $final_mapped_data[$selectedMaintenanceProduct] = 1;
    $data['selectedMaintenanceProduct'] = $selectedMaintenanceProduct;
    $data['selectedMaintenanceProductPrice'] = $selectedMaintenanceProductPrice;
    Mage::getSingleton('customer/session')->setUpgradeRenewal($data);
}

if(!empty($final_mapped_data))
{
	?>
     <ul class="messages">
		<li class="success-msg">
			<ul>
				<li>
                   <span>
						<?php
                        	if(count($discontinued_prod)>0)
							{
								echo $this->__('Licensing file is successfully imported but some products are failed to import as they no longer exist'); ?>(<?php echo implode(', ',$discontinued_prod);?>)
							<?php
							}else{
								echo $this->__('Licensing file is successfully imported');
							}
						?>
					</span>
				</li>
			</ul>
		</li>
	</ul>
    <?php
    if($notificationAboutExpiry){?>

    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li>
                   <span>
                       <?php

                           echo $this->__('Your support license is expiring with in 30 days, please renew it.');

                       ?>
					</span>
                </li>
            </ul>
        </li>
    </ul>
<?php } ?>
	<div>
		<form id="my-quote" name="createquote" action="<?php echo Mage::getUrl('quote/index/save'); ?>" method="post">
			<div class="quotefield">
				<label>Quote Number #: NA</label>
			</div>
			<div class="quotefield">
				<label>End User Organization:</label>
				<input type="text" class="input-text" id="service_number" value="<?php echo $license_file_createdby; ?>" disabled="disabled" />
				<input type="hidden" class="input-text" name="service_number" id="service_number_hidden" value="<?php echo $license_file_createdby; ?>" />
			</div>
			<table class="data-table" id="my-quote-table">
				<col />
				<col />
				<col />
				<col />	
				<col />
				<col />   
				<thead>
					<tr>
						<th><?php echo $this->__('Item') ?></th>
						<th><?php echo $this->__('Item Name') ?></th>
						<th><?php echo $this->__('Item Qty') ?></th>
						<th><?php echo $this->__('Subtotal') ?></th>	                             
					</tr>
				</thead>
				<tbody>
				<?php 
				$softwareProd=0;
				$_odd = '';

//echo $selectedMaintenanceProduct;
//echo $selectedMaintenanceProductPrice;
				foreach ($final_mapped_data as $sku => $qty){
                    if($selectedMaintenanceProduct == $sku)
                if(!strtolower($attribTxt)=='maintenance product') {

                    if(trim($license_data['edition'])=='MF' && (trim($license_data['organization-type'])=='COMMERCIAL') ||(trim
                            ($license_data['organization-type'])=='PROFESSIONAL')){
                            $qty = ceil($license_data['users-licensed']/25) ;

                    }

                    if(trim($license_data['edition'])=='MF' && (trim($license_data['organization-type'])=='EDUCATIONAL')){
                        $qty = ceil($license_data['users-licensed']/500) ;
                    }
                }
                    $_product = Mage::getModel('catalog/product')->loadByAttribute('sku',$sku);
					$attribTxt = $_product->getAttributeText('product_type');
					$item_price=$this->helper('tax')->getPrice($_product, $_product->getFinalPrice($qty));
					//$item_price=number_format($item_price*$qty, '2', '.', ',');
                    $item_price=$item_price*$qty;
					$support=false;
					# Calculate Software products total to calculate price of Support product
					if(strtolower($attribTxt)=='software product')
						$softwareProd=$softwareProd+$item_price;

					# Calculating for support product price

                    if($selectedMaintenanceProduct==''){
					    if(strtolower($attribTxt)=='maintenance product'){
                        $support=true;

						/*$serviceYrs=$qty;
						$qty=1;

						$serviceYrsString=$serviceYrs.' year';
						if($serviceYrs>1)
							$serviceYrsString.='s';
						
						$product = Mage::getModel("catalog/product")->load($_product->getId());
						$optionId=$optionTypeId='';
						$percent=$defaultData='';
						foreach ($product->getOptions() as $o) {
							$values = $o->getValues();
							if ($o->getTitle() == 'Years of Maintenance') { 
								foreach ($values as $v) {
									if(strtolower($v->getTitle())==$serviceYrsString){
										$percent=$v->getprice(); 
										$data=$v->getData();
										$optionId=$data['option_id'];
										$optionTypeId=$data['option_type_id'];
									}

									if(strtolower($v->getTitle())=='1 year')
										$defaultData=$v->getData();
								}
								# nothing is matching we have to take default options
								if($percent==''){
									$percent=$data['price']; 
									$serviceYrs='1';
								}
							}
						}*/
						$percent=$_product->getData('tot_software_perc');

						$calculatedPrice=$softwareProd/100*$percent;

						$item_price=$_product->getFinalPrice($qty);
						
						if($item_price<$calculatedPrice)
							$item_price=$calculatedPrice;

						/*if($_product->getFinalPrice($qty)<$calculatedPrice)
							$item_price=$calculatedPrice;
						else{
							$item_price=$_product->getFinalPrice();
							//$item_price=$item_price+$item_price/100*$defaultPercent;
						}*/
						
					}
                    }

					for($i=0;$i<$qty;$i++){
							$newquote[] = $_product->getId();
					}	

					
				?>
					<tr>
						<td>
							<img src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(75,75); ?>" />
						</td>
						<td>
							<span class="nobr"><?php echo $_product->getName();?></span>
						</td>
						<td>
							<?php echo $qty; $quoteQty[]=$qty;?>
							<input type='hidden' name='qty[<?php echo $_product->getId(); ?>]' value='<?php echo $qty; ?>'>
						</td>	
						<td>
							<?php	
							$filtered = array();
							foreach($license_file_mapdata as $check){
								if($check['sku'] == $sku){				
									$filtered[] = $check;
								}
							}		
							foreach($filtered as $_filter){
								$temp="";			
								$temp = explode('-', $_filter['qty']);		
								if($temp[1]!='above' && $temp[1]!=''){				
									if($qty>=(int)$temp[0] && $qty<=(int)$temp[1]){			
										$item_price = $_filter['price'];
										break;
									}
								}else{			
									$item_price = $_filter['price'];
								}			
							}
                            if($selectedMaintenanceProduct == $sku){
                                $item_price = $selectedMaintenanceProductPrice;
                            }
							//echo $item_price; 		
							$current_currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
							if($current_currency_code == 'NZD'){
									 $price=Mage::helper('directory')->currencyConvert((float)$item_price, 'AUD', 'NZD');				
								echo "NZ$ ".number_format($price, '2', '.', ',');					
							}else{
								echo "AU$ ".number_format($item_price, '2', '.', ',');
							}
							?>		
						</td>           
					</tr>
				<?php } ?>
				 </tbody>
			</table>
            <?php
            Mage::getSingleton('customer/session')->setNewQuote($newquote);
			Mage::getSingleton('customer/session')->setQuoteQty($quoteQty);	

			?>
			<div class="quote" style="float:left;margin:10px 0px">
				<a href="javascript:void(0)" id="licensetoquote" onclick="submitQuote()">SAVE AS QUOTE</a>
			</div>
			<div class="quote" style="float:right;margin:10px 0px">
				<a id="licensequotetocart" href="<?php echo Mage::getUrl('quote/index/licenseQuoteToCart/'); ?>">PLACE ORDER</a>
			</div>
		</form>
	</div>
	<?php 
}else{ 
?>
	<ul class="messages">
		<li class="error-msg">
			<ul>
				<li>
					<span>
					<?php echo $this->__('No items in the license file are matching with product catalogue to generate a quote.'); ?>
					</span>
				</li>
			</ul>
		</li>
	</ul>
<?php
} 
?>
<script type="text/javascript">decorateTable('my-quote-table');</script>
<script type="text/javascript">
jQuery("#service_number").blur(function(){
	jQuery("#service_number_hidden").val(jQuery("#service_number").val());
});
</script>	
