<div class="page-title">
    <h1><?php
        echo $this->__('Quote for the license file') ?></h1>
</div>
<?php
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    // Load the customer's data
        $customer = Mage::getSingleton('customer/session')->getCustomer();
}
$products = Mage::getSingleton('customer/session')->getproducts();
//echo "<pre>";
//print_r($customer);
//exit;
$license_file_createdby =  Mage::getSingleton('core/session')->getLicensefileCreatedBy();
$finalized=$discontinued_prod=$product_with_issues=array();
/**Loop to get the finalized list of products. For this we have to check for product sku in
*license mapping file. if key exists in mapping file then it will be added to the finalized
*list.
**/?>
<?php if(Mage::getSingleton('customer/session')->getNotificationAboutNoProducts()){?>
<ul class="messages">
		<li class="error-msg">
			<ul>
				<li>
					<span>
						<?php
                        echo $this->__("Operation cancelled by user");
						?>
                    </span>
                </li>
            </ul>
        </li>
</ul>
<?php }?>
<?php if(!empty($products)){?>
     	<form id="my-quote" name="createquote" action="<?php echo Mage::getUrl('quote/index/save'); ?>" method="post">
			<div class="quotefield">
				<label>Quote Number #: NA</label>
			</div>
			<div class="quotefield">
				<label>End User Organization:</label>
				<input type="text" class="input-text" id="service_number" value="<?php echo $license_file_createdby; ?>" disabled="disabled" />
				<input type="hidden" class="input-text" name="service_number" id="service_number_hidden" value="<?php echo $license_file_createdby; ?>" />
                <input type="hidden" class="input-text" name="products" id="products" value="<?php print_r($products);
                ?>" />
			</div>
			<table class="data-table" id="my-quote-table">
				<col />
				<col />
				<col />
				<col />	
				<col />
				<col />   
				<thead>
					<tr>
						<th><?php echo $this->__('Item Name') ?></th>
						<th><?php echo $this->__('Item Qty') ?></th>
						<th><?php echo $this->__('Subtotal') ?></th>	                             
					</tr>
				</thead>
				<tbody>
				<?php 
				foreach ($products as $product){
                   $item_price=$product['subtotal'];
                    $qty = $product['quantity'];
                    $item_price=$item_price*$qty;
                    ?>
					<tr>
						<td>
							<span class="nobr"><?php echo $product['name']?></span>
						</td>
                        <td>
                            <?php echo $product['quantity']?>
<!--                            <input type='hidden' name='qty[--><?php //$product['quantity']; ?><!--]' value='--><?php //echo $qty; ?><!--'>-->
                        </td>
                        <td>
                            <?php
                            $current_currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
                            if($current_currency_code == 'NZD'){
                                $price=Mage::helper('directory')->currencyConvert((float)$item_price, 'AUD', 'NZD');
                                echo "NZ$ ".number_format($price, '2', '.', ',');
                            }else{
                                echo "AU$ ".number_format($item_price, '2', '.', ',');
                            }
                            ?>
                        </td>
                    </tr>
				<?php } ?>
				 </tbody>
			</table>
            <?php
//            Mage::getSingleton('customer/session')->setNewQuote($products);


			?>
			<?php if($customer['is_dealer'] || $customer['can_place_order']){?>
			<div class="quote" style="float:right;margin:10px 0px">
				<a id="licensequotetocart" href="<?php echo Mage::getUrl('quote/index/licenseQuoteToCart/'); ?>">PLACE ORDER</a>
			</div>
            <?php } ?>
		</form>
	</div>
	<?php
}else{
?>
<?php
} 
?>
<script type="text/javascript">decorateTable('my-quote-table');</script>
<script type="text/javascript">
jQuery("#service_number").blur(function(){
	jQuery("#service_number_hidden").val(jQuery("#service_number").val());
});
</script>	
