<?php
$collection = Mage::getSingleton('customer/session')->getSubaccountquotes();
$currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
$data = $this->getRequest()->getParams();
$id = $data['id'];
?>
<div class="page-title" id="subaccounts-quote-table">
    <h1><?php echo $this->__('Orders for sub account No.').$id?></h1>
</div>
<div>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<?php if(sizeof($collection)>0): ?>
<table class="data-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Quote #') ?></th>
            <th><?php echo $this->__('Quote Service No.') ?></th>
            <th><?php echo $this->__('Items (Name,Qty)') ?></th>
	    <th><?php echo $this->__('Created Date') ?></th>
<!--	    <th colspan="4" style="text-align:center"><span class="nobr">--><?php //echo $this->__('Actions') ?><!--</span></th>-->
        </tr>
    </thead>
    <tbody>
    <?php foreach ($collection as $quoteId):
        $attributes = array('quote_id'=> $quoteId);
        //$quoteDetails  = Mage::getModel('quote/quote')->loadByAttribute($attributes);
        $quote = Mage::getModel('quote/quote')->getCollection()->addFieldToFilter('quote_id',
            $quoteId);
      //  $quote = $quoteDetails->getData();
        foreach($quote as $q){?>
    <tr>
            <td><?php echo $q['quote_id'] ?>&nbsp;</td>
    <td><?php echo $q['quote_service_num'];?>&nbsp;</td>
    <td><?php
        $productIds = explode(",",$q['quote_product_ids']);
        $productQtys = explode(",",$q['quote_product_qtys']);

        for($i=0;$i<sizeof($productIds);$i++){
            $model = Mage::getModel('catalog/product');
            $_product = $model->load($productIds[$i]);?>
            <table><tr><td style="border: solid 1px"><?php echo $_product->getName(); ?></td><td style="border: solid 1px"><?php echo $productQtys[$i]; ?></td></tr></table>


<?php } ?>&nbsp;</td>
    <td><?php echo date("D, j M, Y", strtotime($q['created_date'])) ?>&nbsp;</td>
    </tr>
  <?php  } ?>
    <?php endforeach ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('subaccounts-quote-table')</script>
<?php else: ?>
    <p><?php echo $this->__('No Quotes found for this account.') ?></p>
<?php endif ?>
