<?php
/**
 * Magento
 * Customized file written by Ramesh Vedula Raybiztech.
 */
?>
<?php
/**
 * Create account form template
 *
 * @see app/design/frontend/base/default/template/customer/form/register.phtml
 */
/** @var $this Mage_Customer_Block_Form_Register */
$formData = Mage::getSingleton('customer/session')->getData('postedData');
Mage::getSingleton('customer/session')->unsetData('postedData');
?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create a Sub Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('paytech/index/createsubaccount') ?>" method="post" id="form-validate">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($formData['email']) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <?php if ($this->isNewsletterEnabled()): ?>
                    <li class="control">
                        <div class="input-box">
                            <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($formData['is_subscribed']): ?> checked="checked"<?php endif; ?> class="checkbox" />
                        </div>
                        <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                    </li>
                <?php endif ?>
                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                <?php if ($_dob->isEnabled()): ?>
                    <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
                <?php endif ?>
                <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                <?php if ($_taxvat->isEnabled()): ?>
                    <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
                <?php endif ?>
                <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                <?php if ($_gender->isEnabled()): ?>
                    <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
                <?php endif ?>
            </ul>
        </div>
        <?php if($this->getShowAddressFields()): ?>
            <div class="fieldset">
                <input type="hidden" name="create_address" value="1" />
                <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
                <ul class="form-list">
                    <li class="fields">
                        <div class="field">
                            <label for="company"><?php echo $this->__('Company') ?></label>
                            <div class="input-box">
                                <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($formData['company']) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                            <div class="input-box">
                                <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($formData['telephone']) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                            </div>
                        </div>
                    </li>
                    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <li class="wide">
                        <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($formData['street'][0]) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <li class="wide">
                            <div class="input-box">
                                <input type="text" name="street[]" value="<?php echo $this->escapeHtml($formData['street'][1]) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                            </div>
                        </li>
                    <?php endfor; ?>
                    <li class="fields">
                        <div class="field">
                            <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                            <div class="input-box">
                                <input type="text" name="city" value="<?php echo $this->escapeHtml($formData['city']) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="region_id"><?php echo $this->__('State/Province') ?></label>
                            <div class="input-box">
                                <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                    //<![CDATA[
                                    $('region_id').setAttribute('defaultValue', "<?php echo $formData['region_id'] ?>");
                                    //]]>
                                </script>
                                <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($formData['region']) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                            <div class="input-box">
                                <input type="text" name="postcode" value="<?php echo $this->escapeHtml($formData['postcode']) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" autocomplete="off"/>
                            </div>
                        </div>
                        <div class="field">
                            <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect(); ?>
                            </div>
                        </div>
                    </li>
                </ul>
                <input type="hidden" name="default_billing" value="1" />
                <input type="hidden" name="default_shipping" value="1" />
            </div>
        <?php endif; ?>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" autocomplete="off" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" autocomplete="off" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="username_papercut"><?php echo $this->__('Username (For Papercut)') ?></label>
                        <div class="input-box">
                            <input type="text" name="username_papercut" id="username_papercut" title="<?php echo $this->__('This is applicable for papercut website') ?>" class="input-text "  autocomplete="off" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="password_papercut"><?php echo $this->__('Password (For Papercut)') ?></label>
                        <div class="input-box">
                            <input type="password_papercut" name="password_papercut" title="<?php echo $this->__('This is applicable for papercut website') ?>" id="password_papercut" class="input-text" autocomplete="off" />
                        </div>
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>
        <div class="field">
            <div class="field name-firstname">
                <label for="order_confirmation_email">Order Confirmation Email(s)
                    (sepreate multiple emails by comma)
                </label>
                <div class="input-box">
                    <input type="text" class="input-text" maxlength="255" title="Order Confirmation Emails" value="<?php echo $customer['order_confirmation_email']; ?>" name="order_confirmation_email" id="order_confirmation_email">
                </div>
            </div>
        </div>
        <ul>
            <li class="control">
                <div class="input-box">
                    <input type="checkbox" name="can_place_order" title="<?php echo $this->__('Can Place Order')
                    ?>" value="1" id="is_subscribed"<?php if($formData['can_place_order']): ?> checked="checked"<?php endif; ?> class="checkbox" />
                </div>
                <label for="can_place_order"><?php echo $this->__('Can Place Order') ?></label>
            </li>
        </ul>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>

    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
        //]]>
        jQuery(document).ready(function($){
            $('#firstname').val('<?php echo $formData[firstname];?>');
            $('#lastname').val('<?php echo $formData[lastname];?>');
            $('#country').val('<?php echo $formData['country_id'];?>');
        });
    </script>
</div>
